### ISSUE TITLE
Is this project dead/archive ?

### ISSUE THREAD

**Issue by ethicnology** [osaxma/schema-dart#10]
Trying to generate the dart code for a simple supabase table from the public schema with no success:

```sh
reading tables...                      found 1 - tables
generating dart source code for tables... /Could not format because the source could not be parsed:

line 2, column 116 of .: Expected an identifier.
  ╷
2 │ class Thing {const Thing({required this.id, required this.createdAt, this.idType, this.arte, this.imdb, this.tmdb, , });
  │                                                                                                                    ^
  ╵
line 20, column 96 of .: Expected an identifier.
   ╷
20 │ Thing copyWith({int? id, DateTime? createdAt, int? idType, String? arte, int? imdb, int? tmdb, , }) { return Thing(id: id ?? this.id,createdAt: createdAt ?? this.createdAt,idType: idType ?? this.idType,arte: arte ?? this.arte,imdb: imdb ?? this.imdb,tmdb: tmdb ?? this.tmdb,); } 
   │                                                                                                ^
   ╵

```

**Comment by osaxma** [comment]
Hi @ethicnology 

I haven't used the project for a while but I just published a version that hopefully fixes the issue:


Give it a try and let me know if it fixed the issue for you:

```
dart pub global activate schema_dart
```

**Comment by ethicnology** [comment]
```sh
reading tables...                       
Severity.error Server does not support SSL, but it was required.
```

**Comment by osaxma** [comment]
Is this a local instance or the remote one? 

Anyway, I added a flag to disable ssl.

Do `dart pub global activate schema_dart` then use the flag as follow:

```
schema-dart --no-ssl -c  <connection-string> -o <output-dir> 
```

let me know if it worked out.

**Comment by ethicnology** [comment]
I'm ssh tunnelling the postgres on my localhost.

Seems to works, but I had to do repeat by pair of table (not possible to chain more than two). I would like to generate for the whole public schema (if you have a hint)
```sh
schema-dart --no-ssl -c postgresql://postgres:"password"@localhost:5432/postgres -o ~/test/ -t table1,table2
```

Also I got a problem with the postgres type `nullable array` or `text[]` `int[]`

generated:
```dart
countries: map['countries'] == null ? null : List<String>?.from(map['countries']),
```
expected:
```dart
countries: map['countries'] == null ? null : List<String>.from(map['countries']),
```

The unnecessary question mark on the List generate:
```sh
A comparison expression can't be an operand of another comparison expression.
Try putting parentheses around one of the comparisons.dart(equality_cannot_be_equality_operand)
```

Except this, seems to work, **thank you for your fast solving !**

Any idea why @supabase doesn't support this project ?

**Comment by ethicnology** [comment]
Also, I think we should make an exception for the two columns `id` and `created_at` (or all timestamps with a postgres function associated) even if they can't be null in postgres,because you don't want to mess up with ID generation and let postgres increment itself and the same for timestamp
```dart
required this.id,
required this.createdAt,
```

**Comment by osaxma** [comment]
> Seems to works, but I had to do repeat by pair of table (not possible to chain more than two). I would like to generate for the whole public schema (if you have a hint)

> Also I got a problem with the postgres type `nullable array` or `text[]` `int[]`
Yes I remember that I didn't account for all cases here.

Good catch -- fixed both of them and pushed a new version to pub.

**Comment by osaxma** [comment]
> Also, I think we should make an exception for the two columns `id` and `created_at` (or all timestamps with a postgres function associated) even if they can't be null in postgres,because you don't want to mess up with ID generation and let postgres increment itself and the same for timestamp
> 
> ```dart
> required this.id,
> required this.createdAt,
> ```

Sorry I am not 100% sure I understand the problem and request here -- can you elaborate?

**Comment by ethicnology** [comment]
I see two usecases in your project:
- [x] Deserialize the row returned by postgREST into classes
- Being able to extend the generated class with custom functions such as insert, update …

```dart
class Thing {

  const Thing({
    required this.id,
    required this.createdAt,
    this.idType,
    …
  });

```

Let's imagine this case, I want to extend the generated class with the insert function, because the `id` is required, I need to assign a number to construct the object and use my `insert()` but in reality you want to let the database assigning the ID itself (as you want to let the database apply the timestamps according to the function you sat up).

The solutions would be to duplicate the generated class to remove the required fields that you want to let the database to manage… Or extending the class giving fake data for required fields in the constructor and ignore them in the `insert()` function

**Actually, what you did totally make sense from the table definition, but it's not convenient to use if you want to reuse these class to make more than just deserializing data.**

For an insertion, you do not provide the `id` or the `created_at` because you usually let the database manage the id increment and the timestamp.

I do not have a good solution in mind right now (except making identifier and timestamps nullable in classes) but we can work on it if you are interested

**Comment by osaxma** [comment]
I see what you mean and it's valid request.

To achieve that, we first need to identify such columns with high certainty.  We can obtain helpful information from the `information_schema.columns` table. 

As an example, I just created a simple table with the following four columns to see how they look on the info table:
- `id`: an auto incrementing primary id
- `id_2`:  an id generated by default using a function
- `value`: a nullable text column
- `created_at`:  timestamp generated by default using a function 

The following subset of columns (e.g. `column_default`, `is_identity` and `identity_generation`) from `information_schema.columns` seem to be helpful for identifying what we're looking for:


| table_name | column_name | column_default    | udt_name    | is_identity | is_nullable | identity_generation | identity_cycle | is_generated | is_updatable |
| ---------- | ----------- | ----------------- | ----------- | ----------- | ----------- | ------------------- | -------------- | ------------ | ------------ |
| temp_table | id          |                   | int8        | YES         | NO          | BY DEFAULT          | NO             | NEVER        | YES          |
| temp_table | id_2        | gen_random_uuid() | uuid        | NO          | YES         |                     | NO             | NEVER        | YES          |
| temp_table | value    |                   | text        | NO          | YES         |                     | NO             | NEVER        | YES          |
| temp_table | created_at  | now()             | timestamptz | NO          | NO          |                     | NO             | NEVER        | YES          |

Given that, we just need to determine how to represent them on the generated class:

- In constructor: requried? nullable? with default value? .. etc
- `toJson` method: should it be there? And in case it's there, should be removed from the generated json if it's null (e.g. in the case it's non-nullable on the table, but also can be inserted/updated by the user when given)


And finally, we just need to have some flags to customize this type of generation.

**Comment by ethicnology** [comment]
Interesting inputs, thank you

Heuristics could be as follows: 
`is_identity is YES` **AND** `identity_generation is not null` **OR** `column_default is not null` 

**=>** The field becomes **nullable** in the class.

It also can be a CLI params for those who don't care about doing something else than deserializing data.

In a dream world it would not make it nullable, and the function would be executed in an alternative constructor/factory which would fill these fields… 

I'm going too far, but, is there a way to execute a single table function ?

**Comment by ethicnology** [comment]
**Off topic**
`in my opinion` we could improve the generated file readability

actually, the output look like this:
```dart
import 'dart:convert';

class Thing {
  const Thing({
    required this.id,
    required this.createdAt,
    this.idType,
    this.arte,
    this.imdb,
    this.tmdb,
  });

  factory Thing.fromMap(Map<String, dynamic> map) {
    return Thing(
      id: int.parse(map['id']),
      createdAt: DateTime.parse(map['created_at']),
      idType: int.tryParse(map['id_type'] ?? ""),
      arte: map['arte'],
      imdb: int.tryParse(map['imdb'] ?? ""),
      tmdb: int.tryParse(map['tmdb'] ?? ""),
    );
  }

  factory Thing.fromJson(String source) => Thing.fromMap(json.decode(source));

  final int id;

  final DateTime createdAt;

  final int? idType;

  final String? arte;

  final int? imdb;

  final int? tmdb;

 // other methods…
}
```

to something like this, fields should be after the class declaration followed by the constructor, functions can be ordered as you want :

```dart
import 'dart:convert';

class Thing {
  final int id;
  final DateTime createdAt;
  final int? idType;
  final String? arte;
  final int? imdb;
  final int? tmdb;

  const Thing({
    required this.id,
    required this.createdAt,
    this.idType,
    this.arte,
    this.imdb,
    this.tmdb,
  });

 // other methods…
}
```

**Comment by ethicnology** [comment]
> `toJson` method: should it be there? And in case it's there, should be removed from the generated json if it's null (e.g. in the case it's non-nullable on the table, but also can be inserted/updated by the user when given)

```dart
  Map<String, dynamic> toMap() {
    return {
      'id': id,
      'created_at': createdAt?.toUtc().toIso8601String(),
      'id_type': idType,
      'arte': arte,
      'imdb': imdb,
      'tmdb': tmdb,
    };
  }
```

Something like this?
```dart
  Map<String, dynamic> toMap() {
    var map = <String, dynamic>{};

    if (id != null) map['id'] = id;
    if (createdAt != null)
      map['created_at'] = createdAt!.toUtc().toIso8601String();
    if (arte != null) map['arte'] = arte;
    if (imdb != null) map['idmb'] = imdb;
    if (tmdb != null) map['tmdb'] = tmdb;

    return map;
  }
```

**Comment by osaxma** [comment]
> **Off topic** `in my opinion` we could improve the generated file readability

I don't have control over the order -- it's the `DartEmitter` from the `code_builder` package which doesn't provide such option. There could be a way to do it, but I bet it'd require some work.


> Something like this?
> 
> ```dart
>   Map<String, dynamic> toMap() {
>     var map = <String, dynamic>{};
> 
>     if (id != null) map['id'] = id;
>     if (createdAt != null)
>       map['created_at'] = createdAt!.toUtc().toIso8601String();
>     if (arte != null) map['arte'] = arte;
>     if (imdb != null) map['idmb'] = imdb;
>     if (tmdb != null) map['tmdb'] = tmdb;
> 
>     return map;
>   }
> ```

Only for fields that are `non-nullable` on the schema. Because if the field is `nullable`, you may wanna set it to `null`. 

This one can be tricky because you also don't want to set something to `null` accidentally.  


> Heuristics could be as follows: `is_identity is YES` **AND** `identity_generation is not null` **OR** `column_default is not null`
> 
> **=>** The field becomes **nullable** in the class.

Sounds reasonable -- I will give it a try when I get a chance.

> It also can be a CLI params for those who don't care about doing something else than deserializing data.

I feel that's the appropriate choice. 

> In a dream world it would not make it nullable, and the function would be executed in an alternative constructor/factory which would fill these fields…

Additional generation is easier than custom generation for sure 😅 

But both sound like the package would evolve into an ORM. 

> I'm going too far, but, is there a way to execute a single table function ?

I am not sure what do you mean by a single table function?

**Comment by osaxma** [comment]
I just thought more about it. 

I am afraid this will be confusing because making a `non-nullable` column as `nullable` would force you to always check if the value is null or to always use null-check operator on them (i.e. `mytable.id!` or `myTable.createdAt!`) even though the column cannot be `null` coming from the database (but can be `null` if you construct the table yourself). 

Null-safety doesn't help here for sure. Maybe providing an option to make all fields nullable would be easier to deal with despite having to do null-checks for each field. 

Also `toJson` wouldn't be helpful here since you need to put these field in a query string for insertion and update, and `toJson` does not do that. Even if you're sending data from the client side to the server side, and then on the server side you're constructing the query, you would still need to go through the fields to validate/sanitize them.

What do you think?

**Comment by osaxma** [comment]
I just did some house keeping in the project.

While I was at it, I pushed a new version with a flag `--nullable-fields`  (shorthand `-n`) that will make all fields of the class nullable.

We can still discuss the other strategies of partial nullability but I would like to hear your thoughts on my last comment.

**Comment by ethicnology** [comment]
> I don't have control over the order -- it's the DartEmitter from the code_builder package which doesn't provide such option. There could be a way to do it, but I bet it'd require some work.

👍

> I am afraid this will be confusing because making a `non-nullable` column as `nullable` would force you to always check if the value is null or to always use null-check operator on them (i.e. `mytable.id!` or `myTable.createdAt!`) even though the column cannot be `null` coming from the database (but can be `null` if you construct the table yourself).

> Null-safety doesn't help here for sure. Maybe providing an option to make all fields nullable would be easier to deal with despite having to do null-checks for each field.

I don't see any others workarounds than accepting the nullity of the fields (except class duplication)

We could have three modes:
1. [x] sticking to the table definition
2. [x] everything is null `--nullable-fields`
3. [ ] partially null when `is_identity is YES` AND `identity_generation is not null` OR `column_default is not null`

We can even split `3` into two other mods:
1. [ ] something like `--null-id` to apply –> `is_identity is YES` AND `identity_generation is not null`
2. [ ] something like `--null-if-column-default` –> `column_default is not null`


> I am not sure what do you mean by a single table function?

I was going too far, it would start to be an ORM you are right

**Comment by osaxma** [comment]
Good idea!

Here's the new version (already published to pub):

```
Generate Data Classes for PostgreSQL schema
  
Examples: 

  # generate data classes for public schema (default)
  schema-dart -c postgresql://postgres:postgres@localhost:54322/postgres -o path/to/output/directory

  # generate for data classes for a "cms" schema 
  schema-dart -c <connection-string> -o <output-dir> -s cms

  # generate data classes for specific tables from public schema (format sensitive): 
  schema-dart -c <connection-string> -o <output-dir> -t "users","posts"
  # or
  schema-dart -c <connection-string> -o <output-dir> --schema=api --tables="profiles","posts"
  

Usage: schema-dart <command> [arguments]

Global options:
-h, --help                 Print this usage information.
-c, --connection-string    PostgreSQL connection string in the following format:
                           postgresql://<username>:<password>@<host>:<port>/<database-name>
-o, --output-dir           The output directory for the generated dart files
-s, --schema               specify the schema
                           (defaults to "public")
-t, --tables=<String>      provide a specific list of tables to generate data classes for.
                           (defaults to all tables)
    --no-ssl               Disable SSL for postgres connection (not recommended)
-n, --nullable-fields      When provided, all fields in generated class will be nullable (useful for partial table queries and for local table construction update/insert)
-i, --nullable-ids         When provided, columns that are identity & have identity generations will be generated as nullable fields
-d, --nullable-defaults    When provided, identity columns that have default values will be generated as nullable fields
-v, --verbose              Enable verbose logging.
    --version              Print the current version.

Available commands:
  help   Display help information for schema-dart.

Run "schema-dart help <command>" for more information about a command.
```

Cheers!

**Comment by ethicnology** [comment]
Thank you a lot for your work

Using `--schema` without `--tables` will exports all table in the given schema right ?

**Comment by osaxma** [comment]
> Thank you a lot for your work

You are welcome 🙏🏽

> Using `--schema` without `--tables` will exports all table in the given schema right ?

Yes exactly.
